### ISSUE TITLE
message send not work

### ISSUE THREAD

**Issue by lyarinet** [AdrianVillamayor/Whatsapp-Api#1]
$ws->send_message()->text("Aloha 🍍", $recipient_id);

first time work after you send template message

text message not working

**Comment by lyarinet** [comment]
it's dork

**Comment by AdrianVillamayor** [comment]
Hii @lyarinet ,

I have tried launching the endpoint repeatedly and it worked fine.

Check that it is not giving any [code](https://developers.facebook.com/docs/whatsapp/cloud-api/support/error-codes)

The most common one is the 131047 Re-engagement message

If not, what response do you get?
