### ISSUE TITLE
message send multiply numbers

### ISSUE THREAD

**Issue by lyarinet** [AdrianVillamayor/Whatsapp-Api#2]
is it possible to message send multiply numbers

**Comment by AdrianVillamayor** [comment]
Hi @lyarinet , 

There is no option in WhatsApp Business Cloud API to send messages to multiple phone numbers at one go, you have to do that one by one or through the loop.

Here is the WhatsApp API doc:
[https://developers.facebook.com/docs/whatsapp/on-premises/reference/messages#sending-messages](https://developers.facebook.com/docs/whatsapp/on-premises/reference/messages#sending-messages)
