### ISSUE TITLE
API not working with the access code

### ISSUE THREAD

**Issue by maddymathan** [AdrianVillamayor/Whatsapp-Api#4]
I have got the access token and when I tried to configure it in the PHP and try to reload the PHP in the browser no error message was displayed and no WhatsApp message to the recipient. Please help to make it

require_once 'vendor/autoload.php';
use Adrii\Whatsapp\Whatsapp;

$graph_version = "v14.0";
$phone_number_id = "105802848942091";
$access_token = "EAAGSBUkK7tsBAB1jHIm5MN3LfnpjOprwrIhjhTowOS8grQeeO8EYCJ1qVDym00KioYQnfMQk5pJMJ3OndrCZCos6of7s1SendmqeNVHA8ZAkQpjwvRb0yfyEyph4PGDFwxuR3aRt4EAhqowNZBKHkzBJYZAOeugBBUOpZAnyvTi8g9ggDCQAMTVRJLsAs8diQ4QMQGbchaQZDZD";
$recipient_id = "918248175266";

$ws = new Whatsapp($phone_number_id, $access_token, $graph_version);

$ws->send_message()->text("Aloha 🍍", $recipient_id);

**Comment by AdrianVillamayor** [comment]
Duplicated #3
