### ISSUE TITLE
How to pass Parameters in components for Template

### ISSUE THREAD

**Issue by Jack-Lanza** [AdrianVillamayor/Whatsapp-Api#5]
I have Template with Variable in body.

`Hello {{1}},`
`We are happy to assist you on your product.`

How can i replace this Variable **`{{1}}`** with name.

I did this using Curl but not able to find in you API.

`// Send message templates defined in the Meta manager.`
`$response = $ws->send_message()->template("sample_issue_resolution", $recipient_id,'en_us',[["type"=> "body", "parameters"=> [ ["type"=> "text","text"=>"name"]]]]);`

**Comment by AdrianVillamayor** [comment]
Hi @Jack-Lanza 

It was not enabled, I just uploaded a new version with an addComponents to add parameters in the templates.

You have everything explained in the commit [v0.51](https://github.com/AdrianVillamayor/Whatsapp-Api/compare/0.44...0.51).

You also have an example in the [Readme.md](https://github.com/AdrianVillamayor/Whatsapp-Api/blob/main/README.md).

Let me know if there is anything else. 

Thanks for your comment🙌🏻
