### ISSUE TITLE
No he podido habilitar el webhook para recibir los mensajes

### ISSUE THREAD

**Issue by rjvelazquez** [AdrianVillamayor/Whatsapp-Api#7]
Hola, estuve probando tu codigo, estoy usando un hosting en hostinger.com, cree el webhook con github pero no se de donde tomar el token que debo colocar en facebook para poder recibir los mensajes de whatsapp. Me disculpo por mi ignorancia, pero si pudieras orientarme un poco te estaria muy agradecido

**Comment by rjvelazquez** [comment]
Estoy atento a tu respuesta

**Comment by rjvelazquez** [comment]
![image](https://user-images.githubusercontent.com/23012216/214321208-05d082b0-febc-4144-aafd-11ee9cba5638.png)

**Comment by rjvelazquez** [comment]
![image](https://user-images.githubusercontent.com/23012216/214321285-4be5014b-b9ef-41dc-af58-49f9fcd47c3f.png)

**Comment by AdrianVillamayor** [comment]
Hola @rjvelazquez ,

Perdona por el lapsus de tiempo, enero es una locura !

De base toda la info que te doy esta en el apartado de [Set up Webhooks](https://developers.facebook.com/docs/whatsapp/business-management-api/guides/set-up-webhooks) te explica detalladamente lo que debes hacer.

En tu caso estas usando los [Webhooks de Github](https://docs.github.com/es/developers/webhooks-and-events/webhooks/about-webhooks), que estan pensados para integraciones, como [GitHub Apps](https://docs.github.com/es/apps/building-github-apps) o [OAuth Apps](https://docs.github.com/es/apps/building-oauth-apps).  

No se como lo tienes configurado pero te recomiendo que revises este ejemplo => [Ejemplo de URL de devolución de llamada para probar webhooks](https://developers.facebook.com/docs/whatsapp/sample-app-endpoints).

La lib esta pensada para un sistema completo, gestionado este los webhooks tanto de validación como de mensajes, por eso te facilita el método `$ws->webhook()->connect($_GET);` .

En tú caso, recomiendo que compruebes que todo esta bien relacionado,  que pruebes el ejemplo que Facebook da, comprueba que tengas los permisos habilitados requeridos, que las variables que devuelve el webook correspondan a la que necesita Facebook, para esto te dejo el endpoint de la lib. que se ocupa de validar y devolver la info que requiere 
=> [Webhook.php](https://github.com/AdrianVillamayor/Whatsapp-Api/blob/main/src/Actions/Webhook.php
) asi lo puedes comparar.

Cualquier duda o problema me dices !

Gracias por tu ayuda 🙌🏻
