### ISSUE TITLE
Creation of dynamic property Adrii\Whatsapp\Actions\Messages::$http_request is deprecated

### ISSUE THREAD

**Issue by nye** [AdrianVillamayor/Whatsapp-Api#8]
**Describe the bug**
I'm getting this error message:

`Creation of dynamic property Adrii\Whatsapp\Actions\Messages::$http_request is deprecated`

I've got it with php 8.2, downgraded to 8.1.13 and still getting the same error

I guess just adding `private $http_request;` should be enought...

And the same occurs with class `Whatsapp`:

```
private $messages;
private $webhook;
```

And class `CurlHelper`

```
private $sent;
```

**Comment by AdrianVillamayor** [comment]
Hi @nye ,

I have just uploaded a new version, [0.7.0](https://github.com/AdrianVillamayor/Whatsapp-Api/releases/tag/0.7.0), which fixes all the bugs of dynamic property creation.

You have it all documented in the [Readme.me](https://github.com/AdrianVillamayor/Whatsapp-Api/blob/main/README.md) and in the [Changelog](https://github.com/AdrianVillamayor/Whatsapp-Api/compare/0.6...0.7.0).

I hope I solved your problem, anything else let me know.

Thank you very much for your help 🙌🏻.

**Comment by nye** [comment]
Thank you very much!!
